spring.datasource.url=jdbc:postgresql://localhost:5432/eFikas
spring.datasource.username=postgres
spring.datasource.password=toor
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


jwt.secret=tRBqDFOY2p9Hy6DriT0grh8QnHzWhnzGHmXHX9G06JU=
jwt.token.validity=86400000

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

aws.region=eu-central-1
aws.bucket-name=software-dev-s3-bucket
aws.credentials.access-key-id=AKIA23AQA3VWF5OREXBX
aws.credentials.secret-access-key=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

oauth2.client.registration.google.client-id=786051698518-n4ihr9cfpjvn05fgnijooivejitj6917.apps.googleusercontent.com